(() => {
  const app = window.ShanHai;

  const LOCATIONS = [
    {
      id: "yunze",
      name: "云泽渡",
      short: "云泽",
      x: 220,
      y: 390,
      region: "水乡",
      danger: 1,
      marketBias: "herb",
      marketTier: 0,
      aura: 26,
      terrain: "水泽与古渡",
      desc: "水网纵横的商埠，药农、行脚商与散修在此交换第一手消息。",
      actions: ["meditate", "hunt", "trade"],
      neighbors: ["qinghe", "misty", "blackforge"],
      resource: "云泽灵草",
      realmId: "marsh-manor",
      tags: ["market", "starter"],
      factionIds: [],
    },
    {
      id: "qinghe",
      name: "青禾镇",
      short: "青禾",
      x: 395,
      y: 445,
      region: "平原",
      danger: 1,
      marketBias: "grain",
      marketTier: 0,
      aura: 20,
      terrain: "田镇与河道",
      desc: "凡人与低阶修士混居的小镇，资源平稳，适合练功和补给。",
      actions: ["meditate", "train", "trade"],
      neighbors: ["yunze", "lantern", "blackforge"],
      resource: "青禾谷露",
      realmId: null,
      tags: ["town"],
      factionIds: ["qinghe-commons"],
    },
    {
      id: "misty",
      name: "迷雾林",
      short: "迷林",
      x: 470,
      y: 250,
      region: "林海",
      danger: 2,
      marketBias: "wood",
      marketTier: 1,
      aura: 34,
      terrain: "迷雾丛林",
      desc: "常年雾瘴不散，潜伏着灵兽与迷失剑客，适合搜寻稀有材料。",
      actions: ["hunt", "quest", "meditate"],
      neighbors: ["yunze", "blackforge", "snowpeak", "starfall"],
      resource: "雾心藤",
      realmId: "mist-hunt",
      tags: ["wild"],
      factionIds: ["mist-hunt-lodge"],
    },
    {
      id: "blackforge",
      name: "玄铁城",
      short: "玄铁",
      x: 700,
      y: 390,
      region: "矿岭",
      danger: 3,
      marketBias: "ore",
      marketTier: 2,
      aura: 30,
      terrain: "火山矿脉",
      desc: "铸器师与护镖修士聚集的重镇，装备交易旺盛，黑市拍卖隐于夜色。",
      actions: ["trade", "train", "auction"],
      neighbors: ["yunze", "qinghe", "misty", "lantern", "redcliff"],
      resource: "玄铁精砂",
      realmId: null,
      tags: ["market", "forge"],
      factionIds: ["blackforge-guild"],
    },
    {
      id: "snowpeak",
      name: "寒魄峰",
      short: "寒魄",
      x: 710,
      y: 115,
      region: "雪原",
      danger: 4,
      marketBias: "ice",
      marketTier: 3,
      aura: 44,
      terrain: "雪峰洞府",
      desc: "冰脉环绕的高峰，适合闭关，也容易遭遇争夺寒魄精华的强敌。",
      actions: ["meditate", "breakthrough", "hunt"],
      neighbors: ["misty", "starfall", "jadegate"],
      resource: "寒魄晶",
      realmId: "ice-cavern",
      tags: ["cultivation"],
      factionIds: [],
    },
    {
      id: "lantern",
      name: "灯海古港",
      short: "古港",
      x: 890,
      y: 510,
      region: "海港",
      danger: 2,
      marketBias: "relic",
      marketTier: 2,
      aura: 24,
      terrain: "海港与夜市",
      desc: "夜市不灭的港口，远航商队带来外海奇珍，也是拍卖行最活跃的城市。",
      actions: ["trade", "auction", "quest"],
      neighbors: ["qinghe", "blackforge", "redcliff", "jadegate"],
      resource: "潮生珀",
      realmId: "tide-ruins",
      tags: ["port", "market"],
      factionIds: ["tide-market"],
    },
    {
      id: "redcliff",
      name: "赤霞崖",
      short: "赤崖",
      x: 1085,
      y: 355,
      region: "绝壁",
      danger: 5,
      marketBias: "fire",
      marketTier: 4,
      aura: 52,
      terrain: "丹霞绝壁",
      desc: "天火曾坠之地，秘境频开，适合高风险高收益的试炼和机缘争夺。",
      actions: ["hunt", "quest", "breakthrough"],
      neighbors: ["blackforge", "lantern", "jadegate", "starfall"],
      resource: "赤焰砂",
      realmId: "ember-palace",
      tags: ["boss"],
      factionIds: [],
    },
    {
      id: "starfall",
      name: "星坠谷",
      short: "星谷",
      x: 1100,
      y: 125,
      region: "秘境",
      danger: 6,
      marketBias: "scroll",
      marketTier: 5,
      aura: 60,
      terrain: "陨星裂谷",
      desc: "天地灵机浓郁的险地，古老残卷与异象齐现，适合寻找顶级功法。",
      actions: ["quest", "hunt", "breakthrough"],
      neighbors: ["misty", "snowpeak", "redcliff", "jadegate"],
      resource: "陨星残页",
      realmId: "star-sanctum",
      tags: ["boss", "endgame"],
      factionIds: [],
    },
    {
      id: "jadegate",
      name: "玉阙山门",
      short: "玉阙",
      x: 1285,
      y: 295,
      region: "宗门",
      danger: 3,
      marketBias: "pill",
      marketTier: 3,
      aura: 56,
      terrain: "山门灵脉",
      desc: "诸多弟子来往的宗门重地，可以闭关突破、拜访长老，也容易卷入门内派系。",
      actions: ["meditate", "train", "breakthrough", "quest", "sect"],
      neighbors: ["snowpeak", "lantern", "redcliff", "starfall"],
      resource: "玉阙灵泉",
      realmId: null,
      tags: ["sect", "cultivation"],
      factionIds: ["jadegate-order"],
    },
  ];

  const LOCATION_MAP = Object.fromEntries(LOCATIONS.map((location) => [location.id, location]));

  app.tables = {
    ...app.tables,
    LOCATIONS,
    LOCATION_MAP,
  };
})();